framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          secret-token
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    validation:      false
    default_locale:  en
    trusted_hosts:   ~
    trusted_proxies: ~
    http_method_override: true
